/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 flatdesign.gltf --transform
Author: peewee.id (https://sketchfab.com/p2eweeworld)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flat-design-web-b12df26ec16749d1abb589cceac9d1d1
Title: Flat Design WEB
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/flatdesign-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.010']} position={[-0.95, 0.585, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.946, 0.069, 1]} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.016']} position={[-0.95, 0.585, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.946, 0.069, 1]} />
      <mesh geometry={nodes.Cube001_0.geometry} material={materials['Material.012']} position={[-1.936, 0.26, 0.024]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.522, 0.074, 0.692]} />
      <mesh geometry={nodes.Cube002_0.geometry} material={materials['Material.018']} position={[0.769, 0.511, 0.024]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.935, 0.074, 0.443]} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.014']} position={[0.769, 0.511, 0.024]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.935, 0.074, 0.443]} />
      <mesh geometry={nodes.Cylinder_0.geometry} material={materials['Material.019']} position={[-3.628, 1.867, 0.066]} scale={[0.108, 0.108, 0.061]} />
      <mesh geometry={nodes.Cylinder001_0.geometry} material={materials['Material.017']} position={[-3.314, 1.867, 0.066]} scale={[0.108, 0.108, 0.061]} />
      <mesh geometry={nodes.Cube006_0.geometry} material={materials['Material.005']} position={[0.333, -0.298, -1.147]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.96, 0.124, 1.85]} />
      <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.006']} position={[0.333, -0.298, -1.147]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.96, 0.124, 1.85]} />
      <mesh geometry={nodes.Cube007_0.geometry} material={materials['Material.007']} position={[0.362, -2.007, -1.151]} rotation={[-1.531, 0, 0]} scale={[2.84, 1.576, 0.171]} />
      <mesh geometry={nodes.Cube009_0.geometry} material={materials['Material.009']} position={[3.114, 0.155, 0.336]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.906, 0.082, 0.085]} />
      <mesh geometry={nodes.Cube010_0.geometry} material={materials['Material.011']} position={[3.117, -0.321, 0.387]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.588, 0.017, 0.052]} />
      <mesh geometry={nodes.Cylinder003_0.geometry} material={materials['Material.003']} position={[3.272, 2.808, -1.151]} scale={[0.557, 0.557, 0.117]} />
      <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.004']} position={[3.272, 2.808, -1.151]} scale={[0.557, 0.557, 0.117]} />
      <mesh geometry={nodes.Cube014_0.geometry} material={materials['Material.002']} position={[-3.279, 2.305, -1.019]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.034, 0.043, 0.757]} />
      <mesh geometry={nodes.Cube013_0.geometry} material={materials['Material.020']} position={[0.796, 1.322, 0.032]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.599, 0.052, 0.069]} />
      <mesh geometry={nodes.Mball008_0.geometry} material={materials['Material.024']} position={[-2.581, 3.071, -1.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.356} />
    </group>
  )
}

useGLTF.preload('/flatdesign-transformed.glb')
