/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 paint.gltf --transform
Author: JamesVTong (https://sketchfab.com/JamesVTong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/baroque-style-oil-painting-frame-by-jamesvtong-4ba8f45f197a44488a9f3e8959f78891
Title: Baroque Style Oil Painting Frame by JamesVTong
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/paint-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.029']} position={[0.001, -0.01, -0.049]} rotation={[0, -Math.PI / 2, 0]} scale={0.319} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.028']} position={[0.001, -0.01, -0.049]} rotation={[0, -Math.PI / 2, 0]} scale={0.319} />
      <mesh geometry={nodes.Object_51.geometry} material={materials['Material.030']} position={[0.001, -0.01, -0.049]} rotation={[0, -Math.PI / 2, 0]} scale={0.319} />
    </group>
  )
}

useGLTF.preload('/paint-transformed.glb')
